// react/first-demo/src/components/Signup.js
import { Component } from "react";

export class Signup extends Component {
    render() {
        return (<div>
            <form>
                Name
                <input type="text" name="" id="" class="form-control" formControlName="name" />
                Email <input type="email" name="" id="" class="form-control" formControlName="email" />
                Phone <input type="number" name="" id="" class="form-control" formControlName="phone" />
                Password <input type="password" name="" id="" class="form-control" formControlName="password" />
                Confirm password <input type="password" name="" id="" class="form-control" formControlName="cpassword" />
                Gender <input type="radio" name="gender" id="rdoFemale" formControlName="gender" value="Female" /><label for="rdoFemale">Female</label> &nbsp;
                <input type="radio" name="gender" id="rdoMale" formControlName="gender" value="Male" /><label for="rdoMale">Male</label> &nbsp;
                <input type="radio" name="gender" id="rdoOther" formControlName="gender" value="Other" /><label for="rdoOther">Other</label><br />
                Date Of Birth <input type="date" name="" id="" class="form-control" formControlName="dateOfBirth" />
                <br />
                <input type="submit" value="Sign Up" class="btn btn-success" />&nbsp;
                <input type="reset" value="Reset" class="btn btn-warning" />

            </form>
        </div>);
    }
}

// angular/oct25-demo1/src/app/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder } from '@angular/forms';
import { UserService } from '../user.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {
  signupForm:any;
  constructor(private fb:FormBuilder, private us:UserService) { 
    this.signupForm=this.fb.group({
      username:[],
      password:[],
      cpassword:[],
      firstName:[],
      lastName:[],
      email:[]
    });
  }

  ngOnInit(): void {
  }

  fnSignup()
  {
    this.us.signup(this.signupForm.value).subscribe((data)=>{
      console.log(data);
      
    });    
  }

}

<form class="container text-left" [formGroup]="signupForm">
    User Name: <input type="text" name="" id="" class="form-control" formControlName="username">
    Password: <input type="password" name="" id="" class="form-control" formControlName="password">
    Confirm Password: <input type="password" name="" id="" class="form-control" formControlName="cpassword">
    First Name: <input type="text" name="" id="" class="form-control" formControlName="firstName">
    Last Name: <input type="text" name="" id="" class="form-control" formControlName="lastName">
    Email: <input type="email" name="" id="" class="form-control" formControlName="email"><br>
    <input type="button" value="Sign Up" class="btn btn-success" (click)="fnSignup()">&nbsp;
    <input type="reset" value="Reset" class="btn btn-warning">

</form>
