// angular/oct25-demo1/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'oct25-demo1';
}

<div class="jumbotron">
  <div class="h1 text-center">Our Angular Project</div>
</div>
<div class="row text-center">
  <div class="col-sm-4"><app-login></app-login></div>
  <div class="col-sm-4">2</div>
  <div class="col-sm-4">3</div>
</div>

// react/first-demo/src/App.js
import './App.css';

function App() {
  return (
    <div className="App">

      <div class="jumbotron text-center">
        <h1>My First Bootstrap Page</h1>
        <p>Resize this responsive page to see the effect!</p>
      </div>


      <div class="row">
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
          
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2">
        </div>
        <div class="col-sm-8">          
        </div>
        <div class="col-sm-2">
        </div>
      </div>

    </div>



  );
}

export default App;
