// angular/sourabh-project/src/app/customer/customer.component.ts
import { Component, OnInit } from '@angular/core';
import {  FormBuilder, Validators} from '@angular/forms'
import { CustomerService } from '../customer.service';

@Component({
  selector: 'app-customer',
  templateUrl: './customer.component.html',
  styleUrls: ['./customer.component.css']
})
export class CustomerComponent implements OnInit {
  customerForm:any;
  customers:any;

  constructor(private fb:FormBuilder, private cs:CustomerService) { 
    this.customerForm=this.fb.group({
      id:[],
      name:[],
      phone:[],
      email:[]
    });
  }

  ngOnInit(): void {
    //call the getAllCustomers method of cs
    this.cs.getAllCustomers().subscribe((data)=>{
      this.customers=data;
      console.log(data);
    });
  }

  fnAddCustomer()
  {
    console.log(this.customerForm.value);
    this.cs.addCustomer(this.customerForm.value).subscribe((data)=>console.log(data));    
  }

  fnUpdateCustomer()
  {
    this.cs.updateCustomer(this.customerForm.value).subscribe((data)=>console.log(data));    
  }

  fnDeleteCustomer()
  {
    var id=this.customerForm.controls.id.value;
    console.log(id);
    this.cs.deleteCustomer(id).subscribe((data)=>console.log(data));
    

  }

}

<form [formGroup]="customerForm">
    Id: <input type="number" name="" id="" formControlName="id" class="form-control">
    Name: <input type="text" name="" id="" formControlName="name" class="form-control">
    Phone: <input type="text" name="" id="" formControlName="phone" class="form-control">
    Email: <input type="email" name="" id="" formControlName="email" class="form-control">
    <br>
    <input type="button" value="Add" class="btn btn-success" (click)="fnAddCustomer()">&nbsp;
    <input type="button" value="Update" class="btn btn-warning" (click)="fnUpdateCustomer()">&nbsp;
    <input type="button" value="Delete" class="btn btn-danger" (click)="fnDeleteCustomer()">&nbsp;
</form>
<br>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>Id</th><th>Name</th><th>Phone</th><th>Email</th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let c of customers">
            <td>{{c.id}}</td>
            <td>{{c.name}}</td>
            <td>{{c.phone}}</td>
            <td>{{c.email}}</td>
        </tr>
    </tbody>
</table>

// react/first-demo/src/components/customer.js
import { Component } from "react";
import customerService from "../services/customer-service";



export class Customer extends Component
{
    constructor()
    {
        super();
        this.state={id:'',name:'',phone:'',email:''};
        this.fnAdd=this.fnAdd.bind(this);
        this.fnUpdate=this.fnUpdate.bind(this);
        this.fnDelete=this.fnDelete.bind(this);
        this.fnOnChange=this.fnOnChange.bind(this);
        
    }

    fnAdd()
    {
        // alert('adding');
        console.log(this.state);
        customerService.addCustomer(this.state).then((response)=>{
            console.log(response);
        });   
    }

    fnUpdate()
    {
        console.log(this.state);
        customerService.updateCustomer(this.state).then((response)=>{
            console.log(response);
        });   
    }

    fnDelete()
    {
        console.log(this.state);
        customerService.deleteCustomer(this.state.id).then((response)=>{
            console.log(response);
        });   
    }

    fnOnChange(event)
    {
        this.setState({[event.target.name]:event.target.value});
        console.log(this.state);
    }

    render()
    {
        return(<div class="text-left">
            Id: <input type="number" name="id" class="form-control" onChange={this.fnOnChange} />
            Name: <input type="text" name="name" class="form-control" onChange={this.fnOnChange} />
            Phone: <input type="text" name="phone" class="form-control" onChange={this.fnOnChange} />
            Email: <input type="email" name="email" class="form-control" onChange={this.fnOnChange} /><br/>
            <input type="button" value="Add" class="btn btn-success" onClick={this.fnAdd} />&nbsp;
            <input type="button" value="Update" class="btn btn-warning" onClick={this.fnUpdate} />&nbsp;
            <input type="button" value="Delete" class="btn btn-danger" onClick={this.fnDelete} />
        </div>);
    }
}
